export interface Tutoriel {
  id: number; categorie: string; titre: string;
  description: string; niveau: string; duree: string;
  topic: string;
}

export const TUTORIELS: Tutoriel[] = [
  { id: 1, categorie: 'Poids mystique', titre: 'Comment calculer ton poids mystique ?', description: "Apprends à utiliser la table Abjad pour calculer le poids mystique de n'importe quel nom.", niveau: 'Débutant', duree: '5 min', topic: 'calcul poids mystique table abjad nom prénom' },
  { id: 2, categorie: 'Poids mystique', titre: 'Comprendre le sens de ton poids mystique', description: "Découvre ce que révèle ton poids mystique sur ta personnalité et ton destin.", niveau: 'Débutant', duree: '7 min', topic: 'signification poids mystique personnalité destin élément' },
  { id: 3, categorie: 'Carrés magiques', titre: 'Construire un carré 3x3 Moussalas', description: "Guide pas à pas pour créer un carré magique 3x3 à partir de ton poids mystique.", niveau: 'Débutant', duree: '10 min', topic: 'carré magique 3x3 moussalas construction étapes poids mystique formule subtract divisor' },
  { id: 4, categorie: 'Carrés magiques', titre: 'Construire un carré 4x4 Mourabbah', description: "Apprends à créer le carré 4x4 Mourabbah avec la méthode exacte islamique.", niveau: 'Intermédiaire', duree: '12 min', topic: 'carré magique 4x4 mourabbah construction reste correction threshold layout' },
  { id: 5, categorie: 'Carrés magiques', titre: 'Les carrés magiques avancés 5x5 à 9x9', description: "Maîtrise la construction des grands carrés magiques islamiques.", niveau: 'Expert', duree: '20 min', topic: 'carrés magiques avancés 5x5 6x6 7x7 8x8 9x9 moukhams moussadis moussabbia mouthammin moutassiou formule' },
  { id: 6, categorie: 'Géomancie', titre: 'Introduction à la géomancie africaine', description: "Découvre les bases de la géomancie islamique ouest-africaine et les 16 figures.", niveau: 'Débutant', duree: '8 min', topic: 'géomancie africaine islamique 16 figures introduction bases maisons thème' },
  { id: 7, categorie: 'Géomancie', titre: 'Lire un thème géomantique complet', description: "Apprends à construire et interpréter un thème géomantique complet avec les 16 maisons.", niveau: 'Intermédiaire', duree: '15 min', topic: 'thème géomantique 16 maisons mères filles nièces témoins juge réconciliateur interprétation' },
  { id: 8, categorie: 'Rêves', titre: "Les bases de l'interprétation islamique des rêves", description: "Découvre la science du Tabir al-ru'ya selon Ibn Sirin et la tradition africaine.", niveau: 'Débutant', duree: '8 min', topic: 'interprétation rêves islamique tabir ruya ibn sirin types symboles bons mauvais' },
  { id: 9, categorie: 'Rêves', titre: 'Les symboles principaux dans les rêves', description: "Comprends la signification des symboles les plus courants dans les rêves islamiques et africains.", niveau: 'Intermédiaire', duree: '12 min', topic: 'symboles rêves eau feu maison serpent mort lumière mariage signification islamique africaine' },
  { id: 10, categorie: 'Secrets mystiques', titre: 'Les noms divins dans la pratique mystique', description: "Apprends à utiliser les 99 noms de Dieu dans les talismans et invocations.", niveau: 'Intermédiaire', duree: '10 min', topic: "noms divins asma husna 99 noms talisman invocation usage mystique يا règle sans ال" },
  { id: 11, categorie: 'Secrets mystiques', titre: 'Construire une invocation personnalisée', description: "Guide complet pour créer une invocation mystique personnalisée avec les noms arabes.", niveau: 'Expert', duree: '15 min', topic: 'invocation personnalisée prénom arabe mère noms divins verset construction poids mystique ibn bint' },
  { id: 12, categorie: 'Plantes mystiques', titre: "Les plantes sacrées d'Afrique de l'Ouest", description: "Découvre les principales plantes mystiques africaines et leurs usages spirituels.", niveau: 'Débutant', duree: '10 min', topic: 'plantes mystiques africaines neem karité baobab moringa propriétés spirituelles bambara noms scientifiques' },
  { id: 13, categorie: 'Plantes mystiques', titre: 'Préparer un bain mystique avec les plantes', description: "Apprends à préparer correctement une décoction mystique et un bain rituel efficace.", niveau: 'Intermédiaire', duree: '12 min', topic: 'bain mystique plantes décoction préparation talisman rituel lavage jours durée' },
  { id: 14, categorie: 'Talismans et rituels', titre: 'Écrire un talisman sur une tablette en bois', description: "Guide complet pour écrire un talisman mystique avec encre naturelle sur tablette.", niveau: 'Intermédiaire', duree: '15 min', topic: 'talisman tablette bois encre safran charbon écriture arabe bismillah salat verset carré magique ordre étapes' },
  { id: 15, categorie: 'Talismans et rituels', titre: 'Le zikr et les invocations pour le rituel', description: "Apprends à faire correctement le zikr quotidien pendant le rituel spirituel.", niveau: 'Intermédiaire', duree: '10 min', topic: 'zikr invocations rituel astaghfirullah salat nabi noms divins verset ordre répétitions harakat' },
];
